# Add source files here
EXECUTABLE	:= bitonicsort
# Cuda source files (compiled with cudacc)
CUFILES		:= bitonicsort.cu
# C/C++ source files (compiled with gcc / c++)
CCFILES		:= \

################################################################################
# Rules and targets

include ../../common/common.mk
