# Add source files here
EXECUTABLE	:= radix
# Cuda source files (compiled with cudacc)
CUFILES		:= radix.cu
# C/C++ source files (compiled with gcc / c++)
CCFILES		:= \

################################################################################
# Rules and targets


include common.mk
